name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create SSH key to connect to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ec2_key.pem
        chmod 400 ec2_key.pem

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key_path: ec2_key.pem
        script: |

          # Clone repo if not exists, otherwise pull
          if [ ! -d "/home/ubuntu/scribble/.git" ]; then
            GIT_SSH_COMMAND="ssh -i ./.ssh/deploy-key" git clone git@github.com:paramsgit/scribble.git
          else
            cd /home/ubuntu/scribble
            GIT_SSH_COMMAND="ssh -i ../.ssh/deploy-key" git pull origin main
          fi

          # Run docker compose
          cd /home/ubuntu/scribble
          docker compose down
          docker compose up -d --build
